name: ViewerRun
version: '2.0'
main: me.fedox.viewerrun.ViewerRun
api-version: '1.21'

commands:
  setcreator:
  start:
  queue:
  setspawn:
  pause:
  continue:
  forceskip:
    aliases:
      - skip
  gm:
  tp: